# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"\x07\n\x05\x45mpty\"E\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cpreferred_os\x18\x04 \x01(\t\"<\n\x07NewUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cpreferred_os\x18\x03 \x01(\t\"!\n\tUsersList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"!\n\tOSRequest\x12\x14\n\x0cpreferred_os\x18\x01 \x01(\t2p\n\x0bUserService\x12\x1e\n\x08GetUsers\x12\x06.Empty\x1a\n.UsersList\x12\x1a\n\x07\x41\x64\x64User\x12\x08.NewUser\x1a\x05.User\x12%\n\x0bGetUserByOS\x12\n.OSRequest\x1a\n.UsersListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=93
  _globals['_NEWUSER']._serialized_start=95
  _globals['_NEWUSER']._serialized_end=155
  _globals['_USERSLIST']._serialized_start=157
  _globals['_USERSLIST']._serialized_end=190
  _globals['_OSREQUEST']._serialized_start=192
  _globals['_OSREQUEST']._serialized_end=225
  _globals['_USERSERVICE']._serialized_start=227
  _globals['_USERSERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
